### ISSUE TITLE
GIt Clone plugin fails on rundeck 5.10 release

### ISSUE THREAD

**Issue by madsholme** [rundeck/rundeck#9596]
**Describe the bug**
When a git clone job is runned the output is:

Execution failed: 16532 in project localjobs: [Workflow result: , step failures: {2=PluginFailed: Could not initialize class org.eclipse.jgit.transport.Transport}, Node failures: {rundeck.local=[]}, status: failed]

**My Rundeck detail**

rundeck
apiversion : 52
base : /var/lib/rundeck
build : 5.10.0-20250312
buildGit : v5.10.0-0-gb4afbd2
node : rundeck.aas.its.nja.dk
serverUUID : d2828e01-c8b3-4238-9d9f-da1dd49959a0
version : 5.10.0-20250312

git clone plugin version: 1.0.4

* Rundeck version: 5.10
* install type: rpm
* OS Name/version: Redhat 9.5
* DB Type/version: mysql

**To Reproduce**
1: add a git repo to be cloned with the git plugin

**Expected behavior**
i expected the git repo to be cloned. i can see on my job output it stopped working just after the rundeck was updated to the 5.10 version.

**Comment by evoracer** [comment]
Same problem here since update from 5.9 to 5.10

It looks like jsch is missing in the git-plugin.
Error Message
`Failed executing step plugin [git-clone-step]: java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException`

jcraft/jsch was changed in this commit
https://github.com/rundeck/rundeck/pull/9514/

**Comment by marinhio75** [comment]
Same problem here since update from 5.9 to 5.10

Are there some new news?

**Comment by marinhio75** [comment]
1=PluginFailed: com/jcraft/jsch/JSchException

**Comment by marinhio75** [comment]
Git clone plugin version 1.0.4 is from 2020, i dont think that the prpblem comes from this site

What changed in Rundeck that prevented so many users from working properly?
We've deployed a snapshot of 5.9 to get it working again.
But that's not the solution.

I don't want to be rude, but a certain lack of interest in solving the problem is noticeable

**Comment by madsholme** [comment]
Im just happy it happened now, just as we were about to buy the paid version, i have started to look into alternatives.

**Comment by marinhio75** [comment]
@madsholme and what was the the solution?

**Comment by madsholme** [comment]
@marinhio75 
we are looking into semaphore. we dont use that many scripts that are not ansible any way. 

the way they ignored this error, does not make me want to spend money on them.

**Comment by marinhio75** [comment]
I tried to use Java 11 because of the missing jsch in Java 17 but no changes

**Comment by rameaub** [comment]
Do you have the issues when configuring the SCM import with git or do you have the issue with the git resource model used to import nodes definition from git?

I only have issue with the git resource model for the nodes definition.
Was wondering if it was the same for you.

**Comment by evoracer** [comment]
For me it happens during the git clone workflow step (Clone a Git repository on Rundeck server)

The Problem exists in Rundeck 5.10 and 5.11 both tested with java 11 and 17
With rundeck 5.9 everything is ok.

**Comment by marinhio75** [comment]
@rameaub Ansible Resource Model Source does not refresh the cache properly in system
@otofuserver all plugins using the com/jcraft/jsch/JSch class are not working

@evoracer yeah we tested it same way

**Comment by rameaub** [comment]
any news on this issue? anybody manage to make it work?

**Comment by marinhio75** [comment]
Unfortunately no response,..

**Comment by madsholme** [comment]
new version of rundeck 5.11 same problem..

**Comment by mtcoffee** [comment]
Issue remains in current snapshot rundeck 5.12

**Comment by MegaDrive68k** [comment]
Hi folks, this issue has already been reported internally. Let me add the proper tags here. Thanks for your feedback!

**Comment by mtcoffee** [comment]
Success confirmed with latest docker SNAPSHOT at RD 5.12 and the 1.06 release of the git plugin.

**Comment by otofuserver** [comment]
To fully resolve this issue, it is essential to update the plugin.
The root cause of the problem is that Rundeck switched from com.jcraft:jsch to com.github.mwiede:jsch.
Since com.jcraft:jsch had not been updated for a long time and was causing issues, this change was inevitable.

Official plugins will most likely be fixed simply by updating them.
However, for community-developed or personal plugins, it will be necessary to ask the developer to make the switch.
The worst-case scenario is when the plugin is no longer maintained and the developer is unreachable.

In that case, you’ll have to hope the source code is available and build the plugin yourself.
Fortunately, the modification only requires changing a single line, so it’s simple.
[Documentation](https://github.com/mwiede/jsch) is also available. Good luck!
