### ISSUE TITLE
Command fails when ran with rundeck, passes when ran locally

### ISSUE THREAD

**Issue by shadycuz** [rundeck/rundeck#2533]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: Ubuntu 16.04
* DB Type/version: mysql? postgres? h2?.....not sure =/

**Expected Behavior**
Command ansible all -m ping executes correctly.
```
ansible@rundeck:~$ ansible all -m ping
Ansible01 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
LXD | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
Webhost | SUCCESS => {
```

**Actual Behavior**
```
14:49:03	AnsibleServer	 1. Command	ERROR! The file /etc/ansible/inventory/cac_inv.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x /etc/ansible/inventory/cac_inv.py`.
14:49:03			ERROR! Inventory script (/etc/ansible/inventory/cac_inv.py) had an execution error:  
14:49:03			ERROR! /etc/ansible/inventory/cac_inv.py:2: Error parsing host definition '"""': No closing quotation
14:49:04			Remote command failed with exit status 1
14:49:04			Failed: NonZeroResultCode: Remote command failed with exit status 1
```

**How to reproduce Behavior**
When I run the command locally it works correctly. When running the command from rundeck ad-hoc or in a job it fails. Using verbose output did not show the actual command that was ran, just the SSH info. I believe something is happening with how the command is wrapped or delimited. This worked fine with 2.7.x that I just upgraded from.

**Comment by ahonor** [comment]
Can you check the ownership and permissions to be sure the rundeck service account can access it.

**Comment by shadycuz** [comment]
![image](https://cloud.githubusercontent.com/assets/17090999/26560068/9e0cd882-4481-11e7-8541-447877630793.png)
![image](https://cloud.githubusercontent.com/assets/17090999/26560084/bcbd32e0-4481-11e7-9dad-2549d31efb7f.png)

Rundeck is logging in as user ansible on the node in question. I can log in and run the command fine, but running from rundeck causes the mentioned error.

![image](https://cloud.githubusercontent.com/assets/17090999/26560114/ee6d5752-4481-11e7-9b01-66fc31b9843a.png)

I just downgraded to 2.7.3 and the problem remains... but I'm not sure what version I was originally on when it worked. I had thought it was 2.7 but I dont remember the minor version.

**Comment by shadycuz** [comment]
oh I see... When logging in as user ansible it is not getting the environment variables located in my bash.rc, but it used to? What would cause this? How do I fix?

![image](https://cloud.githubusercontent.com/assets/17090999/26560295/551f34ba-4483-11e7-8a16-6cc719314d26.png)

**Comment by shadycuz** [comment]
okay.... can we delete this from the internet permanently.... I did not set the env variables for the ansible user, I accidentally set them for root and because I 'su ansible' they were still set so the command passed. 

Sorry,
