### PR TITLE
RUN-2211: Fix: restore class to java core library

### LINKED ISSUE #8925: SSHAgent issue after upgrading to 5.1
**Describe the bug**

(i'm sorry i posted twice on rundeck-discuss but my message seems to not be sent)

i accidently upgraded to 5.1 from 5.0 (apt repo) and now no nodes are dispatched with this following error :

```
Failed: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess
Execution failed: 4999510 in project Qualif: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [taskq.local: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {taskq.local=[PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + 
{dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
```

**My Rundeck detail**

* Rundeck version: 5.1
* install type: apt repo
* OS Name/version: ubuntu 20.04
* DB Type/version: mysql

**To Reproduce**
1. upgraded from 5.0.0 to 5.1

**Expected behavior**
nodes are dispatched without issue

**Additional context**

rundeck is running on ubuntu 20.04 with mariadb
ansible 2.9.6
executor : ansible
file copier : ansible

thank you for you help !

here is the complete debug trace :

```
[workflow] beginExecuteNodeStep(taskq.local): NodeDispatch: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
Failed executing node plugin [exec-command] on node taskq.local: java.lang.NoClassDefFoundError: com/dtolabs/rundeck/core/utils/SSHAgentProcess
	at com.rundeck.plugins.ansible.ansible.AnsibleRunner.registerKeySshAgent(AnsibleRunner.java:624)
	at com.rundeck.plugins.ansible.ansible.AnsibleRunner.run(AnsibleRunner.java:456)
	at com.rundeck.plugins.ansible.plugin.AnsibleNodeExecutor.executeCommand(AnsibleNodeExecutor.java:179)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeCommand(ExecutionServiceImpl.java:427)
	at com.dtolabs.rundeck.core.execution.ExecutionService$executeCommand.call(Unknown Source)
	at org.rundeck.plugin.scriptnodestep.CommandNodeStepPlugin.executeNodeStep(CommandNodeStepPlugin.groovy:49)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:169)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:207)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:130)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:61)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:263)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:234)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:111)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:285)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:681)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:76)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:32)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$beginOperation$1(WorkflowEngineOperationsProcessor.java:323)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: com.dtolabs.rundeck.core.utils.SSHAgentProcess
	... 26 more
Failed: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess
[workflow] finishExecuteNodeStep(taskq.local): NodeDispatch: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess
1: Workflow step finished, result: Dispatch failed on 1 nodes: [taskq.local: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]
[workflow] Finish step: 1,NodeDispatch
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] OperationFailed: operation completed, success? false: OperationCompleted(identity=[1], stepNum=1, newState=DataState{state={step.1.result.failedNodes=taskq.local, step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}, stepResultCapture=StepResultCapture{stepResult=Dispatch failed on 1 nodes: [taskq.local: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ], stepSuccess=false, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={}, base=null)}, success=false)
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] WillProcessStateChange: state changes: [1] DataState{state={step.1.result.failedNodes=taskq.local, step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] Update conditional state: {step.1.result.failedNodes=taskq.local, step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] Update conditional state: {workflow.done=true, step.1.start=true, step.1.skip=true}
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] DidProcessStateChange: applied state changes and rules (changed? true): [1] - StateLogger{state=DataState{state={workflow.id=5b4a53c7-892a-4892-8509-d35101bcf3a3, step.1.result.failedNodes=taskq.local, workflow.keepgoing=false, workflow.done=true, step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.start=true, after.step.1=true, step.1.state=failure, workflow.state=started, step.1.skip=true}}}
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] WorkflowEndState: Workflow end state reached.
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] WillShutdown: Workflow engine shutting down (interrupted? false)
[wf:5b4a53c7-892a-4892-8509-d35101bcf3a3] Complete: Workflow complete: [Step{stepNum=1, label='null'}: OperationCompleted(identity=[1], stepNum=1, newState=DataState{state={step.1.result.failedNodes=taskq.local, step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}, stepResultCapture=StepResultCapture{stepResult=Dispatch failed on 1 nodes: [taskq.local: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ], stepSuccess=false, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={}, base=null)}, success=false)]
[workflow] Finish execution:  node-first: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [taskq.local: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {taskq.local=[PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
[Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [taskq.local: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {taskq.local=[PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
Execution failed: 4999511 in project Moodle-Qualif: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [taskq.local: PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {taskq.local=[PluginFailed: com/dtolabs/rundeck/core/utils/SSHAgentProcess + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
```

### PR DESCRIPTION
**Pull request by gschueler**
**Is this a bugfix, or an enhancement? Please describe.**

Fixes #8925 
Restore class removed from rundeck-core library

**Describe the solution you've implemented**

**Describe alternatives you've considered**

**Additional context**

### CODE REVIEW

**Review by ahormazabal — APPROVED** [review]

**Comment by ahormazabal** [comment]
LGTM
