### ISSUE TITLE
PluginApiService NPE on /api/57/plugin/list breaks workflow editor when ResourceFormatGenerator has null description

### ISSUE THREAD

**Issue by kedar9696** [rundeck/rundeck#10360]
**Bug Description**

After upgrading to Rundeck 5.20.x, installing a third-party `ansible-resource-format` ResourceFormatGenerator plugin causes the job workflow editor to show no workflow steps ("No workflow steps"), even though jobs still execute successfully.

The root cause appears to be a server-side NPE when listing plugins:

```
NullPointerException: Cannot get property 'name' on null object
  at PluginApiService.groovy:121
  GET /api/57/plugin/list
```

Startup also logs:
```
Error heating the plugin cache
```

Removing the plugin from `libext` and restarting Rundeck restores the workflow UI.

In `PluginApiService.listPluginsDetailed()` (5.20.1), the ResourceFormatGenerator section collects plugin descriptions without filtering null values before sorting:

```groovy
pluginDescs[rfgs.name] = pluginService.listPlugins(ResourceFormatGenerator, rfgs)
    .collect { it.value.description }
    .sort { a, b -> a.name <=> b.name }  // NPE when description is null
```

Other plugin types in the same method use `.findAll { it.value.description != null }`.

---

**My Rundeck detail**

* **Rundeck version:** 5.20.1-20260518
* **install type:** deb
* **OS Name/version:** Linux (Ubuntu-based)
* **DB Type/version:** H2 (local/dev instance)

---

**To Reproduce**

1. Upgrade Rundeck from 5.4.x to 5.20.x
2. Install `ansible-resource-format-1.0.1.jar` (ResourceFormatGenerator plugin) in `/var/lib/rundeck/libext/`
3. Restart Rundeck
4. Open any existing job with workflow steps → **Workflow** tab
5. Observe "No workflow steps" in the UI (steps exist in DB; jobs still run)
6. Check `/var/log/rundeck/service.log` for NPE on `/api/57/plugin/list` or `Error heating the plugin cache`
7. Remove the plugin from `libext`, restart → workflow steps appear again in the UI

Optional API verification:
```bash
curl -H "X-Rundeck-Auth-Token: <token>" http://<host>:4440/api/57/plugin/list
# Returns 500 with NPE when plugin is installed
```

---

**Expected behavior**

* `/api/57/plugin/list` should return successfully even if a plugin has incomplete/null metadata
* The workflow editor should display existing job workflow steps
* A misbehaving third-party plugin should not break the entire plugin list API or job editor UI

---

**Screenshots**

* Workflow tab displaying "No workflow steps" with plugin installed

<img width="1851" height="981" alt="Image" src="https://github.com/user-attachments/assets/133a8d27-ccdf-4b77-8f6e-32f9e5979143" />

* Same job showing workflow steps correctly after plugin is removed

<img width="1892" height="969" alt="Image" src="https://github.com/user-attachments/assets/937b7683-82d9-40ae-8543-c9f813b8a785" />

---

**Desktop (please complete the following information):**

* **OS:** Linux
* **Browser:** Chrome
* **Version:** (your browser version)

---

**Additional context**

* Third-party plugin: [ansible-resource-format](https://github.com/rundeck-plugins/ansible-resource-format) (archived; ResourceFormatGenerator for `?format=ansible-inventory`)
* Plugin worked on Rundeck 5.4.0 for job execution and inventory export; UI issue surfaced after 5.20 upgrade
* In 5.4.0, ResourceFormatGenerator plugins were listed via `service.listDescriptions()`. In 5.20.x, listing changed to `pluginService.listPlugins()` which can include entries with `null` description when a provider registers but does not implement `Describable` / expose description via `listDescriptions()`
* `RundeckPluginRegistry.listPluginDescriptors()` creates `DescribedPlugin` with `description: null` for providers in `listProviders()` that are not matched in `listDescriptions()`
* Suggested fix: add `.findAll { it.value.description != null }` before `.collect` for ResourceFormatGenerator (and similar unfiltered sections) in `PluginApiService.groovy`, consistent with other plugin types

@fdevans ; could you please check this.
---

**Comment by fdevans** [comment]
Thanks for the thorough diagnosis and the suggested fix — much appreciated.

Good news: this exact NPE was already fixed independently in `PluginApiService.groovy` by [e0d660f58e8](https://github.com/rundeck/rundeck/commit/e0d660f58e8d735ffbcecd51320e95fd2e9616c0) ("Fix PluginApiService null description handling"), which adds `.findAll { it.value.description != null }` before the `.collect { it.value.description }.sort { ... }` chain for every plugin service type in `listPluginsDetailed()`, including the `ResourceFormatGenerator` section you pointed at.

That fix is present in `v6.0.0`, `v6.0.1`, and `v6.1.0` (and later). It was not backported to the 5.20.x line, so on 5.20.1 you'll still hit this with a plugin that has a null description.

Could you re-test on 6.0.1 or 6.1.0 with the `ansible-resource-format` plugin installed and confirm the workflow editor shows steps correctly? If that checks out, we'll close this as fixed by the commit above.
