### ISSUE TITLE
trouble after upgrade to 4.9.0

### ISSUE THREAD

**Issue by peutch** [rundeck/rundeck#8121]
Hi,

**Describe the bug**

After switching from 4.8.0 to 4.9.0 I am facing this following error in the log output of a simple command run ('ls') on any node.

Exception in thread "sshj-Reader-kappa2/10.6.10.25:22" java.lang.NoClassDefFoundError: com/hierynomus/asn1/encodingrules/ASN1Encoder
	at net.schmizz.sshj.signature.SignatureECDSA$Factory256.create(SignatureECDSA.java:40)
	at net.schmizz.sshj.signature.SignatureECDSA$Factory256.create(SignatureECDSA.java:36)
	at com.hierynomus.sshj.key.BaseKeyAlgorithm.newSignature(BaseKeyAlgorithm.java:58)
	at net.schmizz.sshj.transport.kex.AbstractDHG.next(AbstractDHG.java:82)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:388)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:485)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
Caused by: java.lang.ClassNotFoundException: com.hierynomus.asn1.encodingrules.ASN1Encoder
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:58)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:44)
	... 9 more
[sshj-ssh] TransportException: null
Failed: Unknown: null
[wf:e2e5e76b-6f78-4020-9207-f2f50eed4c8f] Cancellation while running step [1]

**My Rundeck detail**

* Rundeck version: 4.9.0
* install type: war
* OS Name/version: Debian Bullseye
* DB Type/version: mariadb

**Expected behavior**

The output of the 'ls' command.

Regards,
Patrice

**Comment by krajster** [comment]
The problem with [**SSHJ-PLIGIN**](https://github.com/rundeck-plugins/sshj-plugin/issues/7).

**Comment by peutch** [comment]
Sorry for the duplication. I have tried to update the plugin replacing the jar with a modified one without any big success. So I got back to 4.8.0, thanks!

**Comment by MegaDrive68k** [comment]
Confirmed on 4.9.0 under Windows Operating System.

To reproduce: dispatch any command against a remote SSH node using SSHJ node executor.

![Screenshot_1](https://user-images.githubusercontent.com/51376003/216110553-554b17d6-75ad-4ce7-b331-f25eaa949726.png)

Only happens onWindows OS. It works on Linux and MacOS operating systems.

Thanks for your feedback @peutch and @krajster

**Comment by peutch** [comment]
In my case it is also happening on a Linux system (Debian Bullseye).

**Comment by MegaDrive68k** [comment]
@peutch  Could you post the result of `java -version` command? Thanks.

**Comment by peutch** [comment]
Here it is:
```
$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)
```
and here is what is reported using the 'systeminfo' in Rundeck using its previous version 4.8.0:
```
os

arch : amd64
name : Linux
version : 5.10.0-13-amd64

jvm

implementationVersion : 11.0.18+10-post-Debian-1deb11u1
name : OpenJDK 64-Bit Server VM
vendor : Debian
version : 11.0.18
```

**Comment by gschueler** [comment]
This was an issue with the SSHJ plugin, which is fixed here https://github.com/rundeck-plugins/sshj-plugin/pull/9
We have created a new version 0.1.4 with the fix, as well as a fix for another issue.
The updated plugin will be in the next release of Rundeck 4.10.0
