### ISSUE TITLE
Jetty error "NoClassDefFoundError" after upgrade to 2.7.1

### ISSUE THREAD

**Issue by theduusK** [rundeck/rundeck#2254]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: deb
* OS Name/version: Debian Wheezy 7.8

**Expected Behavior**

No issues after upgrading :-) 
___

**Actual Behavior**

After upgrading my Rundeck installation from 2.6.9-1 to latest 2.7.1,  I encountered problems with the updated embedded Jetty server while starting up Rundeck:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/server/nio/SelectChannelConnector
        at com.dtolabs.rundeck.RunServer.configureHTTPConnector(RunServer.java:134)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:94)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.nio.SelectChannelConnector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more`

My first assumption was the change in jaas-loginmodule.conf, but that wasn't the solution.

___

**How to reproduce Behavior**

Upgrading Rundeck (2.6.9-1) via dpkg and latest file "rundeck-2.7.1-1-GA.deb",
modifying the mentioned changes in changelog.

___

**Comment by gschueler** [comment]
check if there are any remnant "rundeck-*2.6.9.jar" files

**Comment by gentunian** [comment]
I had the same problem after installing java 1.8 for using the new `rundeck-cli` package. So I set `JAVA_HOME` variable to point java 1.7.

Running `find /var/lib/rundeck/ -iname "*rundeck*2.6*jar"` outputs nothing.

Other hint on this?

**Comment by gentunian** [comment]
Well, looking again the error was similar but not the same:

```
2017-01-31 21:46:39.880:WARN:oeji.SelectorManager:qtp1480010240-12-selector-0: Exception while notifying connection SslConn
ection@127933e{NOT_HANDSHAKING,eio=-1/-1,di=-1} -> HttpConnection@7510c75a{IDLE},g=HttpGenerator{s=START},p=HttpParser{s=ST
ART,0 of 0}
java.lang.ExceptionInInitializerError
        at sun.security.ssl.SSLEngineImpl.initHandshaker(SSLEngineImpl.java:480)
        at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:683)
        at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:756)
        at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:158)
        at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:228)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.createEndPoint(SelectorManager.java:584)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.access$500(SelectorManager.java:319)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector$Accept.run(SelectorManager.java:706)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChange(SelectorManager.java:410)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChanges(SelectorManager.java:397)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processChanges(SelectorManager.java:487)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:448)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:428)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.IllegalArgumentException: Invalid system property jdk.tls.ephemeralDHKeySize
        at sun.security.ssl.ServerHandshaker.<clinit>(ServerHandshaker.java:147)
        at sun.security.ssl.SSLEngineImpl.initHandshaker(SSLEngineImpl.java:480)
        at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:683)
        at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:756)
        at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:158)
        at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:228)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.createEndPoint(SelectorManager.java:584)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.access$500(SelectorManager.java:319)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector$Accept.run(SelectorManager.java:706)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChange(SelectorManager.java:410)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChanges(SelectorManager.java:397)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processChanges(SelectorManager.java:487)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:448)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:428)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
2017-01-31 21:47:09.851:WARN:oeji.SelectorManager:qtp1480010240-11-selector-1: Exception while notifying connection SslConnection@52a8482a{NOT_HANDSHAKING,eio=-1/-1,di=-1} -> HttpConnection@17aadc1b{IDLE},g=HttpGenerator{s=START},p=HttpParser{s=START,0 of 0}
java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.ServerHandshaker
        at sun.security.ssl.SSLEngineImpl.initHandshaker(SSLEngineImpl.java:480)
        at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:683)
        at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:756)
        at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:158)
        at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:228)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.createEndPoint(SelectorManager.java:584)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.access$500(SelectorManager.java:319)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector$Accept.run(SelectorManager.java:706)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChange(SelectorManager.java:410)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChanges(SelectorManager.java:397)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processChanges(SelectorManager.java:487)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:448)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:428)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
2017-01-31 21:47:39.897:WARN:oeji.SelectorManager:qtp1480010240-12-selector-0: Exception while notifying connection SslConnection@6048eab6{NOT_HANDSHAKING,eio=-1/-1,di=-1} -> HttpConnection@1391dbf2{IDLE},g=HttpGenerator{s=START},p=HttpParser{s=START,0 of 0}
java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.ServerHandshaker
        at sun.security.ssl.SSLEngineImpl.initHandshaker(SSLEngineImpl.java:480)
        at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:683)
        at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:756)
        at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:158)
        at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:228)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.createEndPoint(SelectorManager.java:584)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.access$500(SelectorManager.java:319)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector$Accept.run(SelectorManager.java:706)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChange(SelectorManager.java:410)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.runChanges(SelectorManager.java:397)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processChanges(SelectorManager.java:487)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:448)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:428)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gschueler** [comment]
hmm, i see:

> java.lang.IllegalArgumentException: Invalid system property jdk.tls.ephemeralDHKeySize

I think that property was added in java 8.  Perhaps the server is actually using java 8 not 7

**Comment by gentunian** [comment]
@gschueler sry for my english maybe I didn't explain myself correctly. When using java 8 I got that error. When switching to java 1.7 by setting `JAVA_HOME` variable the error is gone. Anyway, I was trying to contribute as I could use java 1.7 without problem with rundeck, and I don't want to mess this issue with another! Regards

**Comment by theduusK** [comment]
Same issue with 2.7.2 -
no old 2.6.x - jars are there.

JRE 1.8 was already used before and the variable is set correctly.

I'm kind of confused about this line in the Upgrade notes:
> If you have customized /etc/rundeck/profile, look at the new contents and move your custom env var changes to a file in /etc/sysconfig/rundeckd.

There is no /etc/sysconfig/rundeckd on my system after upgrading to 2.7.1 or 2.7.2 -
could that may be related?

**Comment by gschueler** [comment]
@theduusK the notes mean that if you modified /etc/rundeck/profile in your earlier rundeck install, then an upgrade, e.g. via rpm, would not overwrite your changes. But since the init script sources that file, and there were changes to the init script, that might cause errors when the init script is invoked. you should use the newer profile file, and put customizations (overridden env vars) into a new /etc/sysconfig/rundeckd file. 

I really am not sure why you would get that error for `jdk.tls.ephemeralDHKeySize`

**Comment by theduusK** [comment]
After a clean re-install of 2.7.2 and empty /etc/rundeck/ and /var/lib/rundeck/ it's working with my previous configuration. But I'm encountering another issue regarding the WebApplicationContext.

With version 2.6.9 the Context was /rundeck as you can see:
> 2017-02-13 11:59:41.416:INFO:/rundeck:Initializing Spring root WebApplicationContext

Since version 2.7.x it was changed to / only which doesn't work with our Nginx ruleset anymore:
> 2017-02-13 11:41:13.601:INFO:/:main: Initializing Spring root WebApplicationContext

My configuration doesn't seem to affect this Context. Was there something changed?
Any way I can re-configure it to /rundeck ?
For now I rolled back to 2.6.9 as the loadbalancer-ruleset isn't working anymore with the new context.

And just a site note: I didn't get the "jdk.tls.ephemeralDHKeySize" error, that was gentunian's issue :)

**Comment by gschueler** [comment]
@theduusK you can change the context.  make sure to update rundeck-config.properties with the correct URL, and add a JVM property `-Dserver.web.context=/rundeck` into the `/etc/sysconfig/rundeckd`

**Comment by theduusK** [comment]
Thanks - it's working with this additional JVM property.
